export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const PRODUCT_DETAILS = "PRODUCT_DETAILS";

export const GET_CATEGORY = "GET_CATEGORY";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";

export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY";

export const ADD_TO_CART = "ADD_TO_CART";
export const USER_PRODUCT_CART = "USER_PRODUCT_CART";
export const DELETE_PRODUCT_FROM_USERCART = "DELETE_PRODUCT_FROM_USERCART";

export const CHECKOUT_PRODUCT = "CHECKOUT_PRODUCT";

export const ADMIN_ALL_CATEGORY = "ADMIN_ALL_CATEGORY";
export const ADMIN_CREATE_CATEGORY = "ADMIN_CREATE_CATEGORY";
export const ADMIN_UPDATE_CATEGORY = "ADMIN_UPDATE_CATEGORY";
export const ADMIN_DELETE_CATEGORY = "ADMIN_DELETE_CATEGORY";
export const ADMIN_SINGLE_CATEGORY = "ADMIN_SINGLE_CATEGORY";

export const ADMIN_ALL_SUB_CATEGORY = "ADMIN_ALL_SUB_CATEGORY";
export const ADMIN_CREATE_SUB_CATEGORY = "ADMIN_CREATE_SUB_CATEGORY";
export const ADMIN_UPDATE_SUB_CATEGORY = "ADMIN_UPDATE_SUB_CATEGORY";
export const ADMIN_DELETE_SUB_CATEGORY = "ADMIN_DELETE_SUB_CATEGORY";
export const ADMIN_SINGLE_SUB_CATEGORY = "ADMIN_SINGLE_SUB_CATEGORY";
export const ADMIN_SUB_FROM_CATEGORY = "ADMIN_SUB_FROM_CATEGORY";

export const ADMIN_ALL_PRODUCT = "ADMIN_ALL_PRODUCT";
export const ADMIN_CREATE_PRODUCT = "ADMIN_CREATE_PRODUCT";
export const ADMIN_UPDATE_PRODUCT = "ADMIN_UPDATE_PRODUCT";
export const ADMIN_DELETE_PRODUCT = "ADMIN_DELETE_PRODUCT";
export const ADMIN_SINGLE_PRODUCT = "ADMIN_SINGLE_PRODUCT";

export const ADMIN_USER_ORDER = "ADMIN_USER_ORDER";

export const ADMIN_ORDER_STATUS = "ADMIN_ORDER_STATUS";

export const USER_ORDER_TRACK = "USER_ORDER_TRACK";

export const CHECKOUT_TO_HISTORY = "CHECKOUT_TO_HISTORY";
